app/routes/agronomist_routes.py
from flask import Blueprint, render_template, session, redirect, url_for, request
from app.database.db_connection import get_db_connection

agronomist_bp = Blueprint('agronomist', __name__, template_folder='../templates/agronomist')

@agronomist_bp.route('/home')
def agronomist_home():
    if 'agronomist_info' in session:
        agronomist_info = session['agronomist_info']
        return render_template('agronomist/agronomist_home.html', agronomist_info=agronomist_info)
    else:
        return redirect(url_for('errors.errors_index'))

@agronomist_bp.route('/agronomist/view-guide')
def agronomist_view_guide():
    if 'agronomist_info' not in session:
        return redirect(url_for('errors.errors_index'))

    page = request.args.get('page', 1, type=int)
    per_page = 20  # Since we want 5 rows and 4 cards per row
    offset = (page - 1) * per_page

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    # Get the total count of items for pagination
    cursor.execute("SELECT COUNT(*) AS total FROM agriculture_items")
    total_items = cursor.fetchone()['total']
    total_pages = (total_items + per_page - 1) // per_page


    cursor.execute("""
        SELECT ai.agriculture_id,
               ai.common_name,
               im.image_path
        FROM agriculture_items ai
        JOIN images im ON ai.agriculture_id = im.agriculture_id AND im.is_primary = 1
        LIMIT %s OFFSET %s
    """, (per_page, offset))

    items = cursor.fetchall()

    cursor.close()
    connection.close()

    return render_template('agronomist/agronomist_view_guide.html', items=items, page=page, total_pages=total_pages)


# @agronomist_bp.route('/agronomist/view-guide-details/<int:agriculture_id>')
# def agronomist_view_guide_details(agriculture_id):
#     if 'agronomist_info' not in session:
#         return redirect(url_for('errors.errors_index'))
#
#     connection = get_db_connection()
#     cursor = connection.cursor(dictionary=True)
#
#     # Prepared statement to prevent SQL injection
#     cursor.execute("""
#         SELECT * FROM agriculture_items ai
#         WHERE ai.agriculture_id = %s
#     """, (agriculture_id,))
#
#     item_details = cursor.fetchone()
#
#     cursor.close()
#     connection.close()
#
#     if item_details is None:
#         return redirect(url_for('errors.errors_index'))
#
#     # Pass the details to the template
#     return render_template('agronomist/agronomist_view_guide_details.html', item_details=item_details)

@agronomist_bp.route('/agronomist/view-guide-details/<int:agriculture_id>')
def agronomist_view_guide_details(agriculture_id):
    if 'agronomist_info' not in session:
        return redirect(url_for('errors.errors_index'))

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    # Fetch item details
    cursor.execute("""
        SELECT * FROM agriculture_items ai
        WHERE ai.agriculture_id = %s
    """, (agriculture_id,))
    item_details = cursor.fetchone()

    # Fetch images for the carousel
    cursor.execute("""
        SELECT image_path FROM images
        WHERE agriculture_id = %s
    """, (agriculture_id,))
    images = cursor.fetchall()

    cursor.close()
    connection.close()

    if item_details is None:
        return redirect(url_for('errors.errors_index'))

    # Pass the details and images to the template
    return render_template('agronomist/agronomist_view_guide_details.html', item_details=item_details, images=images)

app/templates/agronomist/agronomist_base.html
{% extends "base.html" %}

{% block title %}
{% endblock title %}

{% block style %}
{% endblock style %}

{% block content %}
<div class="container">
  <div class="card text-center border-success mb-3">
    <div class="card-header bg-success">
      <ul class="nav nav-underline" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link {% block active_agronomist %}{% endblock active_agronomist %} " id="home-tab" href="{{ url_for('agronomist.agronomist_home') }}" role="tab" aria-controls="home-tab-pane" aria-selected="true" style="color: #FFFFFF;">
{#          <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true" style="color: #FFFFFF;">#}
            &nbsp;&nbsp;&nbsp;
                <svg t="1709796703862" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3008" id="mx_n_1709796703862" width="20" height="20"><path d="M798.7 1003.5H225.3c-67.8 0-122.9-55.1-122.9-122.9V757.8C102.4 599.7 231 471 389.1 471h245.8c158.1 0 286.7 128.6 286.7 286.7v122.9c0 67.8-55.1 122.9-122.9 122.9zM389.1 553c-112.9 0-204.8 91.9-204.8 204.8v122.9c0 22.6 18.4 41 41 41h573.4c22.6 0 41-18.4 41-41V757.8c0-112.9-91.9-204.8-204.8-204.8H389.1zM512 102.4c67.8 0 122.9 55.1 122.9 122.9S579.8 348.2 512 348.2 389.1 293 389.1 225.3 444.2 102.4 512 102.4m0-81.9c-113.1 0-204.8 91.7-204.8 204.8S398.9 430.1 512 430.1s204.8-91.7 204.8-204.8S625.1 20.5 512 20.5z" fill="#ffffff" p-id="3009"></path><path d="M512.9 665.3c-22.5 0-41 18.4-41 41v81.9c0 22.5 18.4 41 41 41 22.5 0 41-18.4 41-41v-81.9c0-22.6-18.5-41-41-41z" fill="#ffffff" p-id="3010"></path></svg>
              &nbsp;
              My Profile
              &nbsp;&nbsp;&nbsp;
{#          </button>#}
          </a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link {% block active_guide %}{% endblock active_guide %}" id="disabled-tab" href="{{ url_for('agronomist.agronomist_view_guide') }}" role="tab" aria-controls="disabled-tab-pane" aria-selected="false" style="color: #FFFFFF;">
{#          <button class="nav-link" id="disabled-tab" data-bs-toggle="tab" data-bs-target="#disabled-tab-pane" type="button" role="tab" aria-controls="disabled-tab-pane" aria-selected="false" style="color: #FFFFFF;">#}
              &nbsp;&nbsp;&nbsp;
                <svg t="1709796606984" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2197" id="mx_n_1709796606985" width="20" height="20"><path d="M839.7 1003.5H184.3c-67.8 0-122.9-55.1-122.9-122.9V225.3c0-67.8 55.1-122.9 122.9-122.9 22.6 0 41 18.3 41 41s-18.3 41-41 41c-22.6 0-41 18.4-41 41v655.4c0 22.6 18.4 41 41 41h655.4c22.6 0 41-18.4 41-41V225.3c0-22.6-18.4-41-41-41s-41-18.3-41-41 18.3-41 41-41c67.8 0 122.9 55.1 122.9 122.9v655.4c0 67.8-55.2 122.9-122.9 122.9z" p-id="2198" fill="#ffffff"></path><path d="M604.2 266.2H419.8c-62.1 0-112.6-50.5-112.6-112.6v-20.5c0-62.1 50.5-112.6 112.6-112.6h184.3c62.1 0 112.6 50.5 112.6 112.6v20.5c0.1 62.1-50.4 112.6-112.5 112.6zM419.8 102.4c-16.9 0-30.7 13.8-30.7 30.7v20.5c0 16.9 13.8 30.7 30.7 30.7h184.3c16.9 0 30.7-13.8 30.7-30.7v-20.5c0-16.9-13.8-30.7-30.7-30.7H419.8zM737.3 491.5H286.7c-22.5 0-41-18.4-41-41 0-22.5 18.4-41 41-41h450.6c22.5 0 41 18.4 41 41-0.1 22.6-18.5 41-41 41zM614.4 737.3H286.7c-22.5 0-41-18.4-41-41 0-22.5 18.4-41 41-41h327.7c22.5 0 41 18.4 41 41 0 22.5-18.5 41-41 41z" p-id="2199" fill="#ffffff"></path></svg>
              &nbsp;
              View Guide
              &nbsp;&nbsp;&nbsp;
{#          </button>#}
          </a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade {% block active_agronomist_show %}{% endblock active_agronomist_show %}" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
            {% block my_profile %}
            {% endblock my_profile %}
        </div>

        <div class="tab-pane fade {% block active_guide_show %}{% endblock active_guide_show %}" id="disabled-tab-pane" role="tabpanel" aria-labelledby="disabled-tab" tabindex="0">
            {% block view_guide %}
            {% endblock view_guide %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

app/templates/agronomist/agronomist_home.html
{% extends "agronomist/agronomist_base.html" %}

{% block title %}
Agronomist Home
{% endblock title %}

{% block active_agronomist %}active{% endblock active_agronomist %}
{% block active_agronomist_show %}show active{% endblock active_agronomist_show %}

{% block my_profile %}
<div class="container" style="width: 50%; margin: auto;">
  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709607318489" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2222" width="20" height="20"><path d="M512 321.6m-262.6 0a262.6 262.6 0 1 0 525.2 0 262.6 262.6 0 1 0-525.2 0Z" fill="#242424" p-id="2223"></path><path d="M924.3 903.6c0-0.1 0-0.1 0 0-0.1-2.1-0.3-4-0.6-5.9C901.2 690.1 725.5 528.6 512 528.6c-213.8 0-389.7 161.9-411.8 369.8-0.2 1.5-0.4 2.9-0.4 4.4 0 0.2-0.1 0.5-0.1 0.7h0.1v1.2c0 22.6 18.3 40.9 40.9 40.9h742.8c22.6 0 40.9-18.3 40.9-40.9 0-0.4-0.1-0.8-0.1-1.1z" fill="#242424" p-id="2224"></path></svg>
    </span>
    <span class="input-group-text" id="basic-addon1">Username</span>
    <input value="{{ session['username'] }}" type="text" id="username" class="form-control" aria-label="username" aria-describedby="button-addon2" readOnly>
    <button class="btn btn-outline-success btn-edit-save" type="button" data-field="username" id="button-username">Edit</button>
  </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709607732614" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2665" width="20" height="20"><path d="M297.4 250.2c22.6 0 41 18.3 41 41V462c0 22.6-18.3 41-41 41-22.6 0-41-18.3-41-41V291.2c0-22.6 18.4-41 41-41zM701.5 246.2c22.6 0 41 18.3 41 41v169.1c0 22.6-18.3 41-41 41-22.6 0-41-18.3-41-41V287.2c0-22.6 18.4-41 41-41z" fill="#242424" p-id="2666"></path><path d="M499.4 126.2c89 0 161.1 72.1 161.1 161.1h81.9c0-134.2-108.8-243-243-243s-243 108.8-243 243h81.9c0-89 72.2-161.1 161.1-161.1zM865.4 938V482.1c-3.4-33.4-31-59.7-64.9-61H200.6c-37.5 0-68 30.4-68.1 67.9v444.3c4 30.2 27.8 54.2 57.9 58.5h621.5c27-5.4 48.3-26.8 53.5-53.8z" fill="#242424" p-id="2667"></path></svg>
    </span>
    <span class="input-group-text" id="basic-addon1">Password</span>
    <input value="" type="text" id="password" class="form-control" aria-label="password" aria-describedby="button-addon2" readOnly>
    <button class="btn btn-outline-success btn-edit-save" type="button" data-field="password" id="button-password">Edit</button>
  </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709607788930" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2888" width="20" height="20"><path d="M663.4 541.2m-40.9 0a40.9 40.9 0 1 0 81.8 0 40.9 40.9 0 1 0-81.8 0Z" fill="#242424" p-id="2889"></path><path d="M643.1 149.2m-40.9 0a40.9 40.9 0 1 0 81.8 0 40.9 40.9 0 1 0-81.8 0Z" fill="#242424" p-id="2890"></path><path d="M989 854.6c0-143.7-85.3-267.5-208-323.6 54.8-43.4 90-110.6 90-185.9 0-127.8-101.2-232-227.9-236.8v81.8c81 4.7 145.2 72.9 145.2 155 0 78.8-56.1 146.7-132.3 156.1-5.6 0.7-12.9 7.4-12.9 13v60.6c0-20 3.1-0.6 7.2-0.3l5 7c143.3 8.7 251.8 127.6 251.8 273.1h0.1v0.8c0 22.6 18.3 40.9 40.9 40.9S989 878 989 855.4v-0.8z" fill="#242424" p-id="2891"></path><path d="M393.5 344.7m-233.4 0a233.4 233.4 0 1 0 466.8 0 233.4 233.4 0 1 0-466.8 0Z" fill="#242424" p-id="2892"></path><path d="M759.9 861.9c-0.1-1.8-0.2-3.6-0.5-5.3-20-184.4-176.2-328-365.9-328-190 0-346.3 143.9-366 328.7-0.2 1.3-0.3 2.6-0.4 4 0 0.2 0 0.4-0.1 0.7v1.1c0 20.1 16.3 36.4 36.4 36.4h660.2c20.1 0 36.4-16.3 36.4-36.4 0-0.5-0.1-0.8-0.1-1.2z" fill="#242424" p-id="2893"></path></svg>
    </span>
    <span class="input-group-text" id="basic-addon1">First Name</span>
    <input value="{{ agronomist_info[0] }}" type="text" id="first_name" class="form-control" aria-label="first_name" aria-describedby="button-addon2" readOnly>
    <button class="btn btn-outline-success btn-edit-save" type="button" data-field="first_name" id="button-first_name">Edit</button>
  </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709607788930" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2888" width="20" height="20"><path d="M663.4 541.2m-40.9 0a40.9 40.9 0 1 0 81.8 0 40.9 40.9 0 1 0-81.8 0Z" fill="#242424" p-id="2889"></path><path d="M643.1 149.2m-40.9 0a40.9 40.9 0 1 0 81.8 0 40.9 40.9 0 1 0-81.8 0Z" fill="#242424" p-id="2890"></path><path d="M989 854.6c0-143.7-85.3-267.5-208-323.6 54.8-43.4 90-110.6 90-185.9 0-127.8-101.2-232-227.9-236.8v81.8c81 4.7 145.2 72.9 145.2 155 0 78.8-56.1 146.7-132.3 156.1-5.6 0.7-12.9 7.4-12.9 13v60.6c0-20 3.1-0.6 7.2-0.3l5 7c143.3 8.7 251.8 127.6 251.8 273.1h0.1v0.8c0 22.6 18.3 40.9 40.9 40.9S989 878 989 855.4v-0.8z" fill="#242424" p-id="2891"></path><path d="M393.5 344.7m-233.4 0a233.4 233.4 0 1 0 466.8 0 233.4 233.4 0 1 0-466.8 0Z" fill="#242424" p-id="2892"></path><path d="M759.9 861.9c-0.1-1.8-0.2-3.6-0.5-5.3-20-184.4-176.2-328-365.9-328-190 0-346.3 143.9-366 328.7-0.2 1.3-0.3 2.6-0.4 4 0 0.2 0 0.4-0.1 0.7v1.1c0 20.1 16.3 36.4 36.4 36.4h660.2c20.1 0 36.4-16.3 36.4-36.4 0-0.5-0.1-0.8-0.1-1.2z" fill="#242424" p-id="2893"></path></svg>
    </span>
    <span class="input-group-text" id="basic-addon1">Last Name</span>
    <input value="{{ agronomist_info[1] }}" type="text" id="last_name" class="form-control" aria-label="last_name" aria-describedby="button-addon2" readOnly>
    <button class="btn btn-outline-success btn-edit-save" type="button" data-field="last_name" id="button-last_name">Edit</button>
  </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709607808930" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3110" width="20" height="20"><path d="M963.8 212.3c-2.1 7.6-6.5 14.7-13 20.1L531.7 584.3c-0.2 0.2-0.4 0.4-0.7 0.5-16.4 13.2-40.3 11.6-54.8-3.3L126.6 288.9c-17.2-14.4-19.5-40.3-5.1-57.6 14.4-17.2 40.3-19.5 57.6-5.1l326.4 273.3 392.7-329.6c5.1-4.3 10.9-7.1 17-8.5-6.5-1.9-13.3-3-20.4-3H113.2c-39.1 0-71.1 32-71.1 71.1V822c0 39.1 32 71.1 71.1 71.1h781.6c39.1 0 71.1-32 71.1-71.1V229.5c0-5.9-0.7-11.7-2.1-17.2z" fill="#242424" p-id="3111"></path></svg>
    </span>
    <span class="input-group-text" id="basic-addon1">Email</span>
    <input value="{{ agronomist_info[2] }}" type="text" id="email" class="form-control" aria-label="email" aria-describedby="button-addon2" readOnly>
    <button class="btn btn-outline-success btn-edit-save" type="button" data-field="email" id="button-email">Edit</button>
  </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709607828248" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3332" width="20" height="20"><path d="M532.7 100.4l22 78.9c85.2-28 182.7-8.1 250.5 59.7 62.8 62.8 79.5 161.7 60.1 242.1 20.1 7.9 52.2 17.7 77.1 27.9 28.3-111.1 8.8-241.7-78.3-328.9-89.8-89.6-218.3-115.2-331.4-79.7z" fill="#242424" p-id="3333"></path><path d="M516.178373 168.417637a40.9 40.9 0 1 0 57.840325-57.842345 40.9 40.9 0 1 0-57.840325 57.842345Z" fill="#242424" p-id="3334"></path><path d="M728.960896 471.541445a40.9 40.9 0 1 0 57.840325-57.842344 40.9 40.9 0 1 0-57.840325 57.842344Z" fill="#242424" p-id="3335"></path><path d="M576.789113 319.277565a40.9 40.9 0 1 0 57.840325-57.842345 40.9 40.9 0 1 0-57.840325 57.842345Z" fill="#242424" p-id="3336"></path><path d="M873.974908 526.213272a40.9 40.9 0 1 0 57.840325-57.842344 40.9 40.9 0 1 0-57.840325 57.842344Z" fill="#242424" p-id="3337"></path><path d="M597.5 250.1l13.8 80.7c28-3.7 57.4 5.3 78.9 26.8 21.1 21.1 30.1 49.8 27 77.4l64 17.3c0.4-0.5 0.9-1.1 1.4-1.6 4.5-4.5 10.8-6.1 16.1-4.6 6.5-52.2-10.3-106.7-50.3-146.7-40.6-40.5-98.1-56.5-150.9-49.3z" fill="#242424" p-id="3338"></path><path d="M938.2 840.4c1.8-3.2 3.2-6.7 4.1-10.4 4.8-17 7.4-34.9 7.4-53.5 0-108.8-88.2-197-197-197-92.3 0-169.8 63.6-191.2 149.3-121.8-54.4-216.3-159.6-255.9-289.2 84.6-22.1 147.1-99 147.1-190.6v-0.9-0.9c0-108.1-87.7-195.8-195.8-195.8-27.3 0-53.3 5.6-76.9 15.7-71.2 29.8-121.3 100-121.3 182 0 2.8 0.1 5.6 0.2 8.4-0.1 4.8-0.2 9.6-0.2 14.4 0 387.5 314.2 700.6 701.7 700.6 2.9 0 5.8-0.2 8.6-0.2 3.4-0.1 6.8-0.7 9.9-1.7 74.4-9.8 135.5-61.3 159.3-130.2z" fill="#242424" p-id="3339"></path></svg>
    </span>
    <span class="input-group-text" id="basic-addon1">Phone Number</span>
    <input value="{{ agronomist_info[3] }}" type="text" id="phone_number" class="form-control" aria-label="phone_number" aria-describedby="button-addon2" readOnly>
    <button class="btn btn-outline-success btn-edit-save" type="button" data-field="phone_number" id="button-phone_number">Edit</button>
  </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709607862671" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3556" width="20" height="20"><path d="M267 901.5h40.9-16.2c-13.8-0.8-24.7-12.2-24.7-26.2v26.2zM674 900.5h40.9-16.2c-13.8-0.8-24.7-12.2-24.7-26.2v26.2z" fill="#242424" p-id="3557"></path><path d="M754.8 900.5h-40.9 16.2c13.8-0.8 24.7-12.2 24.7-26.2v26.2zM348.8 900.5h-40.9 16.2c13.8-0.8 24.7-12.2 24.7-26.2v26.2zM592.7 737.2h-40.9H568c13.8 0.8 24.7 12.2 24.7 26.2v-26.2zM836.6 573.7h40.9-16.2c-13.8 0.8-24.7 12.2-24.7 26.2v-26.2zM185.2 573.7h-40.9 16.2c13.8 0.8 24.7 12.2 24.7 26.2v-26.2zM429.6 737.2h40.9-16.2c-13.8 0.8-24.7 12.2-24.7 26.2v-26.2z" fill="#242424" p-id="3558"></path><path d="M953.7 573.3c11.4 0.8 23.1-3.1 31.9-11.9 16-16 16-41.9 0-57.9l-445.1-445c-8.2-8.2-18.9-12.1-29.6-12-10.7-0.2-21.4 3.8-29.6 12l-445.1 445c-1.6 1.6-3.1 3.4-4.4 5.2-5.3 6.9-8.5 15.5-8.5 24.9 0 22.6 18.3 40.9 40.9 40.9h120.9V914c0 37.6 30.5 68.1 68.1 68.1h0.5v0.1H362.4c34.7 0 63.3-26 67.5-59.5V737.5h162.3l0.4 122V914c0 37.6 30.5 68.1 68.1 68.1h0.5v0.1H769.4c34 0 62.2-25 67.3-57.6v-351" fill="#242424" p-id="3559"></path></svg>
    </span>
    <span class="input-group-text" id="basic-addon1">Address</span>
    <input value="{{ agronomist_info[4] }}" type="text" id="address" class="form-control" aria-label="address" aria-describedby="button-addon2" readOnly>
    <button class="btn btn-outline-success btn-edit-save" type="button" data-field="address" id="button-address">Edit</button>
  </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709797169015" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="4066" width="20" height="20"><path d="M287.1 51.8c22.6 0 41 18.3 41 41v98.1c0 22.6-18.3 41-41 41-22.6 0-41-18.3-41-41V92.7c0.1-22.6 18.4-40.9 41-40.9zM731.1 51.8c22.6 0 41 18.3 41 41v98.1c0 22.6-18.3 41-41 41-22.6 0-41-18.3-41-41V92.7c0-22.6 18.4-40.9 41-40.9z" fill="#242424" p-id="4067"></path><path d="M78.3 309.3h865.5c22.6 0 41 12 41 28V170.9c0-38.7-31.3-70-70-70H804V192c0 39.2-31.7 70.9-70.9 70.9s-70.9-31.7-70.9-70.9v-91.1H361V192c0 39.2-31.7 70.9-70.9 70.9s-70.9-31.7-70.9-70.9v-91.1H108.8c-38.7 0-70 31.3-70 70v168.4c4.8-17.3 20.7-30 39.5-30zM943.7 391.2H78.3c-18.8 0-34.7-12.7-39.5-30v543.4c0 38.7 31.3 70 70 70h805.9c38.7 0 70-31.3 70-70V364.3c-4 14.9-18.3 26.9-41 26.9z" fill="#242424" p-id="4068"></path><path d="M759.3 488.1c-16-16-41.9-16-57.9 0L456.1 733.4 332.2 609.5c-16-16-41.9-16-57.9 0s-16 41.9 0 57.9l150.5 150.5c8.6 8.6 20.1 12.6 31.4 11.9 11.3 0.7 22.8-3.3 31.4-11.9l271.8-271.8c15.9-16 15.9-42-0.1-58z" fill="#FFFFFF" p-id="4069"></path></svg>
    </span>
    <span class="input-group-text" id="basic-addon1">Date Joined</span>
    <input value="{{ agronomist_info[5] }}" type="text" id="date_joined" class="form-control" aria-label="date_joined" aria-describedby="button-addon2" readOnly>
  </div>
</div>
{% endblock my_profile %}

{% block scripts %}

{% endblock scripts %}

app/templates/agronomist/agronomist_view_guide.html
{% extends "agronomist/agronomist_base.html" %}

{% block title %}
View Guide
{% endblock title %}

{% block style %}
<style>
  .card-custom-col {
    padding-left: 1px;
    padding-right: 1px;
    padding-bottom: 5px;
  }
  .img-custom-size {
    width: 10rem;
    height: 10rem;
    object-fit: cover;
  }
</style>
{% endblock style %}

{% block active_guide %}active{% endblock active_guide %}
{% block active_guide_show %}show active{% endblock active_guide_show %}

{% block view_guide %}

{% for item_chunk in items | batch(5, '&nbsp;') %}
<div class="row">
    {% for item in item_chunk %}
    <div class="col card-custom-col">
        <div class="card" style="width: 10rem;">
            <img src="{{ item.image_path }}" class="card-img-top img-custom-size" alt="{{ item.common_name }}">
            <div class="card-body">
                <h6 class="card-title">{{ item.common_name }}</h6>
                <a href="{{ url_for('agronomist.agronomist_view_guide_details', agriculture_id=item.agriculture_id) }}" class="btn btn-outline-success">
                    Learn more
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endfor %}

<div class="row">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-end">
        <li class="page-item {% if page <= 1 %}disabled{% endif %}">
          <a class="page-link" href="?page={{ page - 1 }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>

        {% for p in range(1, total_pages + 1) %}
        <li class="page-item {% if p == page %}active{% endif %}">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endfor %}
        <li class="page-item {% if page >= total_pages %}disabled{% endif %}">
          <a class="page-link" href="?page={{ page + 1 }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
</div>

{% endblock view_guide %}

{% block scripts %}

{% endblock scripts %}