app/routes/auth_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, jsonify
from werkzeug.security import check_password_hash, generate_password_hash
from ..database.db_connection import get_db_connection
import re

auth_bp = Blueprint('auth', __name__, template_folder='../templates')


def render_toast(type, message):
    return {'type': type, 'message': message}

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    global redirect_url
    error = None
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        connection = get_db_connection()
        cursor = connection.cursor(prepared=True)
        sql = "SELECT user_id, password_hash, role_name FROM users WHERE status='active' AND username=%s"
        cursor.execute(sql, (username,))
        user_record = cursor.fetchone()

        if user_record and check_password_hash(user_record[1], password):

            session['user_id'] = user_record[0]
            session['username'] = username
            session['role'] = user_record[2]
            cursor.close()

            if session['role'] == 'agronomist':
                redirect_url = url_for('agronomist.agronomist_home')

                connection = get_db_connection()
                cursor = connection.cursor(prepared=True)

                agronomist_info_sql = "SELECT first_name, last_name, email, phone_number, address, date_joined FROM agronomists WHERE user_id=%s"
                cursor.execute(agronomist_info_sql, (session['user_id'],))
                agronomist_info = cursor.fetchone()
                session['agronomist_info'] = agronomist_info
                cursor.close()
                connection.close()


            elif session['role'] == 'staff':
                redirect_url = url_for('staff.staff_home')

                connection = get_db_connection()
                cursor = connection.cursor(prepared=True)

                staff_info_sql = "SELECT first_name, last_name, email, work_phone_number, hire_date, position, department FROM staff_and_administrators WHERE user_id=%s"
                cursor.execute(staff_info_sql, (session['user_id'],))
                staff_info = cursor.fetchone()
                session['staff_info'] = staff_info
                cursor.close()
                connection.close()


            elif session['role'] == 'administrator':
                redirect_url = url_for('admin.admin_home')

                connection = get_db_connection()
                cursor = connection.cursor(prepared=True)

                admin_info_sql = "SELECT first_name, last_name, email, work_phone_number, hire_date, position, department FROM staff_and_administrators WHERE user_id=%s"
                cursor.execute(admin_info_sql, (session['user_id'],))
                admin_info = cursor.fetchone()
                session['admin_info'] = admin_info
                cursor.close()
                connection.close()

            # Return a JSON response with the redirect URL
            return jsonify(success=True, redirect_url=redirect_url)

        else:
            cursor.close()
            connection.close()

            toast = render_toast('danger', 'Invalid username or password. Please try again.')
            return jsonify(success=False, toast=toast), 401

    return render_template('login.html')

@auth_bp.route('/logout')
def logout():

    session.clear()
    return redirect(url_for('auth.login'))

@auth_bp.route('/sources')
def sources():
    return render_template('sources.html')

def is_password_complex(password):
    complexity_check = re.compile('^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{8,}$')
    return complexity_check.match(password)

@auth_bp.route('/register/agronomist', methods=['GET', 'POST'])
def register_agronomist():
    if request.method == 'POST':
        form_data = {
            'username': request.form['username'],
            'password': request.form['password'],
            'first_name': request.form['first_name'],
            'last_name': request.form['last_name'],
            'email': request.form['email'],
            'phone_number': request.form['phone'],
            'address': request.form['address'],
        }

        if not is_password_complex(form_data['password']):

            toast = render_toast('danger', 'Password must contain at least 8 characters, including uppercase and lowercase letters, numbers, and special characters.')
            return jsonify(success=False, form_data=form_data, toast=toast), 422

        connection = get_db_connection()
        cursor = connection.cursor(prepared=True)
        cursor.execute('SELECT * FROM users WHERE username = %s', (form_data['username'],))
        existing_user = cursor.fetchone()
        if existing_user:
            toast = render_toast('danger', 'Username already exists. Please choose a different username.')
            return jsonify(success=False, form_data=form_data, toast=toast), 409

        hashed_pwd = generate_password_hash(form_data['password'])
        insert_user_sql = (
            'INSERT INTO users (username, password_hash, role_name, status) '
            'VALUES (%s, %s, %s, %s)'
        )
        cursor.execute(insert_user_sql, (form_data['username'], hashed_pwd, 'agronomist', 'active'))
        user_id = cursor.lastrowid

        insert_agronomist_sql = (
            'INSERT INTO agronomists (user_id, first_name, last_name, email, phone_number, address, date_joined) '
            'VALUES (%s, %s, %s, %s, %s, %s, CURDATE())'
        )
        cursor.execute(insert_agronomist_sql, (user_id, form_data['first_name'], form_data['last_name'], form_data['email'], form_data['phone_number'], form_data['address']))

        connection.commit()
        cursor.close()
        connection.close()

        toast = render_toast('success', 'Congratulations! Registration successful.')
        return jsonify(success=True, form_data=form_data, toast=toast)

    return render_template('register_for_agronomist.html', form_data=None)


@auth_bp.route('/register/admin', methods=['GET', 'POST'])
def register_admin():
    if request.method == 'POST':
        form_data = {
            'username': request.form['username'],
            'password': request.form['password'],
            'first_name': request.form['first_name'],
            'last_name': request.form['last_name'],
            'email': request.form['email'],
            'work_phone_number': request.form['phone'],
            'position': request.form['position'],
            'department': request.form['department'],
        }

        if not is_password_complex(form_data['password']):

            toast = render_toast('danger', 'Password must contain at least 8 characters, including uppercase and lowercase letters, numbers, and special characters.')
            return jsonify(success=False, form_data=form_data, toast=toast), 422

        connection = get_db_connection()
        cursor = connection.cursor(prepared=True)
        cursor.execute('SELECT * FROM users WHERE username = %s', (form_data['username'],))
        existing_user = cursor.fetchone()
        if existing_user:
            toast = render_toast('danger', 'Username already exists. Please choose a different username.')
            return jsonify(success=False, form_data=form_data, toast=toast), 409


        hashed_pwd = generate_password_hash(form_data['password'])
        insert_user_sql = (
            'INSERT INTO users (username, password_hash, role_name, status) '
            'VALUES (%s, %s, %s, %s)'
        )
        cursor.execute(insert_user_sql, (form_data['username'], hashed_pwd, 'administrator', 'active'))
        user_id = cursor.lastrowid

        insert_admin_sql = (
            'INSERT INTO staff_and_administrators (user_id, first_name, last_name, email, work_phone_number, hire_date, position, department) '
            'VALUES (%s, %s, %s, %s, %s, CURDATE(), %s, %s)'
        )
        cursor.execute(insert_admin_sql, (user_id, form_data['first_name'], form_data['last_name'], form_data['email'], form_data['work_phone_number'], form_data['position'], form_data['department']))

        connection.commit()
        cursor.close()
        connection.close()

        toast = render_toast('success', 'Congratulations! Registration successful.')
        return jsonify(success=True, form_data=form_data, toast=toast)

    return render_template('register_for_admin.html', form_data=None)



@auth_bp.route('/register/staff', methods=['GET', 'POST'])
def register_staff():
    if request.method == 'POST':
        form_data = {
            'username': request.form['username'],
            'password': request.form['password'],
            'first_name': request.form['first_name'],
            'last_name': request.form['last_name'],
            'email': request.form['email'],
            'work_phone_number': request.form['phone'],
            'position': request.form['position'],
            'department': request.form['department'],
        }

        if not is_password_complex(form_data['password']):
            toast = render_toast('danger', 'Password must contain at least 8 characters, including uppercase and lowercase letters, numbers, and special characters.')
            return jsonify(success=False, form_data=form_data, toast=toast), 422

        connection = get_db_connection()
        cursor = connection.cursor(prepared=True)
        cursor.execute('SELECT * FROM users WHERE username = %s', (form_data['username'],))
        existing_user = cursor.fetchone()
        if existing_user:
            toast = render_toast('danger', 'Username already exists. Please choose a different username.')
            return jsonify(success=False, form_data=form_data, toast=toast), 409

        hashed_pwd = generate_password_hash(form_data['password'])
        insert_user_sql = (
            'INSERT INTO users (username, password_hash, role_name, status) '

app/templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0"
                class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://cdn.pixabay.com/photo/2017/07/19/08/50/gardening-2518377_1280.jpg"
                 class="d-block w-100" alt="Gardening" style="height:500px; object-fit:cover;">
            <div class="carousel-caption d-none d-md-block">
                <h5>Understanding Pests</h5>
                <p>Get to know the pests that might be harming your green space. Our pest directory includes Argentine Stem Weevil, Black Beetle, Clover Root Weevil, Diamondback Moth, and many more.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://cdn.pixabay.com/photo/2014/07/05/08/30/lawn-mower-384589_1280.jpg"
                 class="d-block w-100" alt="Lawn Mower" style="height:500px; object-fit:cover;">
            <div class="carousel-caption d-none d-md-block">
                <h5>Weed Identification</h5>
                <p>Our comprehensive directory also enlists various weed species that can invade your property, from Barley Grass, Black Nightshade, Creeping Buttercup to Oxeye Daisy and more.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://cdn.pixabay.com/photo/2021/10/19/07/00/sunflower-6722698_1280.jpg"
                 class="d-block w-100" alt="Sunflower" style="height:500px; object-fit:cover;">
            <div class="carousel-caption d-none d-md-block">
                <h5>Comprehensive Pest and Weed Directory</h5>
                <p>Stay one step ahead with our detailed directory, containing large varieties of pests and weeds. Leveraging this knowledge can help maintain a healthy and thriving garden landscape.</p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<div class="container-fluid d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card mb-3" style="max-width: 800px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://cdn.pixabay.com/photo/2015/05/28/21/26/detective-788592_1280.jpg" class="img-fluid rounded-start" style="height: 100%; object-fit: cover;" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <form  id="login-form" method="POST">
                        <div class="input-group input-group-lg mb-3">
                            <span class="input-group-text">
                                <svg t="1709607318489" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2222" width="20" height="20"><path d="M512 321.6m-262.6 0a262.6 262.6 0 1 0 525.2 0 262.6 262.6 0 1 0-525.2 0Z" fill="#242424" p-id="2223"></path><path d="M924.3 903.6c0-0.1 0-0.1 0 0-0.1-2.1-0.3-4-0.6-5.9C901.2 690.1 725.5 528.6 512 528.6c-213.8 0-389.7 161.9-411.8 369.8-0.2 1.5-0.4 2.9-0.4 4.4 0 0.2-0.1 0.5-0.1 0.7h0.1v1.2c0 22.6 18.3 40.9 40.9 40.9h742.8c22.6 0 40.9-18.3 40.9-40.9 0-0.4-0.1-0.8-0.1-1.1z" fill="#242424" p-id="2224"></path></svg>
                            </span>
                            <input type="text" name="username" aria-label="Username" class="form-control" placeholder="Username" required>
                        </div>

                        <div class="input-group input-group-lg mb-3">
                            <span class="input-group-text">
                                <svg t="1709607366991" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2441" width="20" height="20"><path d="M309.4 244.9c22.6 0 41 18.3 41 41v170.8c0 22.6-18.3 41-41 41-22.6 0-41-18.3-41-41V285.9c0.1-22.6 18.4-41 41-41zM713.5 240.9c22.6 0 41 18.3 41 41v23.4c0 22.6-18.3 41-41 41-22.6 0-41-18.3-41-41v-23.4c0.1-22.6 18.4-41 41-41z" fill="#242424" p-id="2442"></path><path d="M511.5 120.9c89 0 161.1 72.1 161.1 161.1h81.9c0-134.2-108.8-243-243-243s-243 108.8-243 243h81.9c0-89 72.1-161.1 161.1-161.1zM877.4 932.6V476.8c-3.4-33.4-31-59.7-64.9-61H212.7c-37.5 0-68 30.4-68.1 67.9V928c4 30.2 27.8 54.2 57.9 58.5H824c27-5.5 48.2-26.8 53.4-53.9z" fill="#242424" p-id="2443"></path><path d="M436.9 701.1c0-22.6 18.3-41 41-41h66.2c22.6 0 41 18.3 41 41 0 22.6-18.3 41-41 41h-66.2c-22.6-0.1-41-18.4-41-41z" fill="#FFFFFF" p-id="2444"></path></svg>
                            </span>
                            <input type="password" name="password" aria-label="Password" class="form-control" placeholder="Password" required>
                        </div>
                        <div class="d-grid mb-5">
                            <button type="submit" class="btn btn-outline-success btn-lg">Login</button>
                        </div>
                    </form>
                    <p class="card-text">
                        Don't have an account yet? Register as <a href="{{ url_for('auth.register_agronomist') }}" style="color: #38DB44;">agronomist</a> now!
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/login.js') }}"></script>
{% endblock %}

app/templates/register_for_admin.html
{% extends "register_for_staff.html" %}

{% block title %}
Register for Admin
{% endblock %}

{% block form %}action="/auth/register/admin"{% endblock %}

app/templates/register_for_staff.html
{% extends "register_for_agronomist.html" %}

{% block title %}
  Register for Staff
{% endblock %}

{% block form %}action="/auth/register/staff"{% endblock %}

{% block extra_fields %}
    <div class="input-group mb-2">
        <span class="input-group-text">
            <svg t="1709607828248" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3332" width="20" height="20"><path d="M532.7 100.4l22 78.9c85.2-28 182.7-8.1 250.5 59.7 62.8 62.8 79.5 161.7 60.1 242.1 20.1 7.9 52.2 17.7 77.1 27.9 28.3-111.1 8.8-241.7-78.3-328.9-89.8-89.6-218.3-115.2-331.4-79.7z" fill="#242424" p-id="3333"></path><path d="M516.178373 168.417637a40.9 40.9 0 1 0 57.840325-57.842345 40.9 40.9 0 1 0-57.840325 57.842345Z" fill="#242424" p-id="3334"></path><path d="M728.960896 471.541445a40.9 40.9 0 1 0 57.840325-57.842344 40.9 40.9 0 1 0-57.840325 57.842344Z" fill="#242424" p-id="3335"></path><path d="M576.789113 319.277565a40.9 40.9 0 1 0 57.840325-57.842345 40.9 40.9 0 1 0-57.840325 57.842345Z" fill="#242424" p-id="3336"></path><path d="M873.974908 526.213272a40.9 40.9 0 1 0 57.840325-57.842344 40.9 40.9 0 1 0-57.840325 57.842344Z" fill="#242424" p-id="3337"></path><path d="M597.5 250.1l13.8 80.7c28-3.7 57.4 5.3 78.9 26.8 21.1 21.1 30.1 49.8 27 77.4l64 17.3c0.4-0.5 0.9-1.1 1.4-1.6 4.5-4.5 10.8-6.1 16.1-4.6 6.5-52.2-10.3-106.7-50.3-146.7-40.6-40.5-98.1-56.5-150.9-49.3z" fill="#242424" p-id="3338"></path><path d="M938.2 840.4c1.8-3.2 3.2-6.7 4.1-10.4 4.8-17 7.4-34.9 7.4-53.5 0-108.8-88.2-197-197-197-92.3 0-169.8 63.6-191.2 149.3-121.8-54.4-216.3-159.6-255.9-289.2 84.6-22.1 147.1-99 147.1-190.6v-0.9-0.9c0-108.1-87.7-195.8-195.8-195.8-27.3 0-53.3 5.6-76.9 15.7-71.2 29.8-121.3 100-121.3 182 0 2.8 0.1 5.6 0.2 8.4-0.1 4.8-0.2 9.6-0.2 14.4 0 387.5 314.2 700.6 701.7 700.6 2.9 0 5.8-0.2 8.6-0.2 3.4-0.1 6.8-0.7 9.9-1.7 74.4-9.8 135.5-61.3 159.3-130.2z" fill="#242424" p-id="3339"></path></svg>
        </span>
        <input type="tel" aria-label="Phone" class="form-control" placeholder="Phone" id="phone" name="phone" value="{{ form_data.work_phone_number if form_data else '' }}" required>
    </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709608111065" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3772" width="20" height="20"><path d="M929.2 228.4L523.5 34.9c-11.9-8.1-27.8-9.7-41.6-2.8L60.6 244.2c-0.5 0.2-0.9 0.5-1.4 0.7-8.2 3.9-15.1 10.5-19.3 19.3-9.7 20.4-1.1 44.9 19.3 54.6l412 196.5c2 0.9 4 1.7 6 2.3 9.9 3.3 21.2 2.8 31.2-2.3l346-174.2v261c0 22.6 18.3 41 41 41 22.6 0 41-18.3 41-41v-303c8.4-6.4 13.7-15.6 15.4-25.6 3.6-18-5.3-36.8-22.6-45.1z" fill="#242424" p-id="3773"></path><path d="M818.1 458.3c-7.5-13.3-22.8-20.8-38.4-20.2h-1.3c-6.5 0.4-12.6 2.2-17.9 5L489.3 565.7 255.5 465.6c-5.8-2.8-12.3-4.3-19.3-4.3-22.6 0-41 16.5-41 36.7v219.4c0 0.6 0 1.3 0.1 1.9 2.3 99.8 141.8 180.3 313.4 180.3 170.8 0 309.7-79.7 313.4-178.7 0.1-0.8 0.1-1.5 0.1-2.3V478.4c0.8-6.7-0.5-13.7-4.1-20.1z" fill="#242424" p-id="3774"></path></svg>
    </span>
    <input type="text" aria-label="Position" class="form-control" placeholder="Position" id="position" name="position" value="{{ form_data.position if form_data else '' }}" required>
  </div>

  <div class="input-group mb-2">
    <span class="input-group-text">
        <svg t="1709608144108" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3991" width="20" height="20"><path d="M70.6 267.1c11.3-19.6 36.4-26.3 55.9-15l372.8 215.3 369.1-213.1c19.6-11.3 44.6-4.6 55.9 15 0.2 0.3 0.3 0.5 0.4 0.8-3.5-7-8.9-13-16.2-17.2L521.7 29.5c-7.5-6.1-16.9-9.3-26.4-9.2-9.5-0.1-18.9 3.1-26.4 9.2l-383 221.1c-10.1 5.8-16.8 15.4-19.3 25.9 0.9-3.1 2.2-6.3 4-9.4z" fill="#242424" p-id="3992"></path><path d="M925.5 271.5c9.6 19.2 2.7 42.9-16.2 53.8L543.4 536.5v429c0 22.6-18.3 41-41 41-22.6 0-41-18.3-41-41V540.1l-375.9-217c-11.9-6.9-19.1-18.8-20.3-31.6v446.1c-1.5 15.5 5.9 31.1 20.3 39.4l387.4 223.7c7.5 6.1 16.9 9.3 26.4 9.2 9.5 0.1 18.9-3.1 26.4-9.2l376-217.1c16.6-5.2 28.7-20.7 28.7-39.1V290.9c0-7.1-1.8-13.7-4.9-19.4z" fill="#242424" p-id="3993"></path></svg>
    </span>
    <input type="text" aria-label="Department" class="form-control" placeholder="Department" id="department" name="department" value="{{ form_data.department if form_data else '' }}" required>
  </div>
{% endblock %}

app/templates/sources.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="container">
                <div class="card text-center mb-3">
                    <div class="card-header bg-success">
                        <a href="https://pixabay.com/zh/photos/" style="color: #FFFFFF;" class="me-2">Image</a>
                        <a href="https://www.iconfont.cn/" style="color: #FFFFFF;" class="me-2">SVG</a>
                        <a href="https://agpest.co.nz/pest-directory/" style="color: #FFFFFF;" class="me-2">Pest & Weed directory</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
{% endblock %}